network:
  version: 2
  renderer: networkd
  ethernets:
    end0:
      dhcp4: yes
      dhcp4-overrides:
        use-dns: true
        use-routes: true
      link-local: []
      addresses: [192.168.153.15/24]
      optional: true
