network:
  version: 2
  renderer: networkd
  ethernets:
    end0:
      dhcp4: true
      link-local: [ipv4]   # Erlaube automatisch 169.254.x.x wenn DHCP fehlt
      optional: true
    wlan0:
      optional: true
  bridges:
    br0:
      optional: true
